language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database bookstore;' -U postgres
  - cp config/database.yml.travis config/database.yml
addons:
  postgresql: "9.6"
env:
  global:
  - PGPORT=5432
# Run the unit test
script:
  #- export PATHONPATH=`pwd`
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python initialize_database initialize_books.py
  - python initialize_database initialize_database.py
  - python initialize_database initialize_search_database.py
  - coverage run --timid --branch --source fe,be --concurrency=thread -m pytest -v --ignore=fe/data

# Push the results back to codecov
after_success:
  - coverage combine
  - coverage report
  - codecov
