language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt
services:
  - postgresql

addons:
  postgresql: "9.6"  # I'm just using this, if you're using another version, might need to fix the pg_hba.conf path below
before_install:
  # stop old version
  - sudo /etc/init.d/postgresql stop
  # add postgresql 10 repository
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  # install new version
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-10 postgresql-client-10
  # clone auth config (might need to fix source path for another version)
  - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
  # start new version
  - sudo /etc/init.d/postgresql restart
  # I haven't investigated or tried to fix, but pg10 uses another port
  # for some reason, so tell applications to use correct port
  - export PGPORT=5433
before_script:
  - psql -c 'create database bookstore;' -U postgres
  - cp config/database.yml.travis config/database.yml
# Run the unit test
script:
  #- export PATHONPATH=`pwd`
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python initialize_database initialize_books.py
  - python initialize_database initialize_database.py
  - python initialize_database initialize_search_database.py
  - coverage run --timid --branch --source fe,be --concurrency=thread -m pytest -v --ignore=fe/data

# Push the results back to codecov
after_success:
  - coverage combine
  - coverage report
  - codecov
