language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt


sudo: required
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - bash install-postgres-10.sh
# Run the unit test
script:
  #- export PATHONPATH=`pwd`
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python initialize_books.py
  - python initialize_database.py
  - python initialize_search_database.py
  - coverage run --timid --branch --source fe,be --concurrency=thread -m pytest -v --ignore=fe/data

# Push the results back to codecov
after_success:
  - coverage combine
  - coverage report
  - codecov
